export default [
  {
    id: 1,
    img: "m1.jpg",
    title: "Round neck shirt",
    price: "1450",
    rating: "5",
    starImage: "star.png",
    istrending: true,
  },
  {
    id: 2,
    img: "m2.jpg",
    title: "Round neck shirt",
    price: "1250",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 3,
    img: "m3.jpg",
    title: "Round neck shirt",
    price: "1000",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 4,
    img: "m4.jpg",
    title: "Round neck shirt",
    price: "4150",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 5,
    img: "m5.jpg",
    title: "Round neck shirt",
    price: "1450",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 6,
    img: "m6.jpg",
    title: "Round neck shirt",
    price: "1150",
    rating: "5",
    starImage: "star.png",
    istrending: true,
  },
  {
    id: 7,
    img: "m7.jpg",
    title: "Round neck shirt",
    price: "2250",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 8,
    img: "m8.jpg",
    title: "Round neck shirt",
    price: "1150",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 9,
    img: "m9.jpg",
    title: "Round neck shirt",
    price: "1000",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 10,
    img: "m10.jpg",
    title: "Round neck shirt",
    price: "2000",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 11,
    img: "m11.jpg",
    title: "2 sleeve shirt",
    price: "2100",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 12,
    img: "m12.jpg",
    title: "2 sleeve shirt",
    price: "2200",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 13,
    img: "m13.jpg",
    title: "2 sleeve shirt",
    price: "1800",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 14,
    img: "m14.jpg",
    title: "2 sleeve shirt",
    price: "1700",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 15,
    img: "m15.jpg",
    title: "2 sleeve shirt",
    price: "2700",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 16,
    img: "m16.jpg",
    title: "2 sleeve shirt",
    price: "1110",
    rating: "5",
    starImage: "star.png",
    istrending: true,
  },
  {
    id: 17,
    img: "m17.jpg",
    title: "2 sleeve shirt",
    price: "2220",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 18,
    img: "m18.jpg",
    title: "2 sleeve shirt",
    price: "1900",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 19,
    img: "m19.jpg",
    title: "Zara jeans",
    price: "1300",
    rating: "5",
    starImage: "star.png",
    istrending: true,
  },
  {
    id: 20,
    img: "m20.jpg",
    title: "Zara jeans",
    price: "1750",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 21,
    img: "m21.jpg",
    title: "Zara jeans",
    price: "1990",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 22,
    img: "m22.jpg",
    title: "Zara jeans",
    price: "2000",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 23,
    img: "m23.jpg",
    title: "Zara jeans",
    price: "2100",
    rating: "5",
    starImage: "star.png",
    istrending: true,
  },
  {
    id: 24,
    img: "m24.jpg",
    title: "Zara jeans",
    price: "1450",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },
  {
    id: 25,
    img: "m25.jpg",
    title: "Zara jeans",
    price: "2250",
    rating: "5",
    starImage: "star.png",
    istrending: false,
  },

];
